name = "biotfo-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "biotfo-db"
database_id = "599aba38-a12f-4655-a2e9-fa239c7f6beb"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "biotfo-assets"

[[kv_namespaces]]
binding = "CACHE"
id = "20630d1d0cf343aaa74d29a30abaa697"

[vars]
FRONTEND_URL = "https://biotfo-web.pages.dev"
ASSETS_URL = "https://biotfo-worker.diaoyudao110.workers.dev"

[triggers]
crons = ["*/1 * * * *"]
